# Copyright (c) 2025 Mazey-Jessica Emily Twilight
# Copyright (c) 2025 UnifiedGaming Systems Ltd (Company Number: 16108983)
# Licensed under the Apache License, Version 2.0
# http://www.apache.org/licenses/LICENSE-2.0
